#!/usr/bin/env python3
"""
OpenSploit MCP Server: evil-winrm

WinRM command execution and file transfer using pypsrp.
pypsrp natively supports the PowerShell plugin URI, avoiding the CMD
shell Invoke restriction that blocks pywinrm on Windows Server 2025
for non-admin WinRM users.
"""

import os
import re
import shutil
from typing import Optional

from mcp_common import BaseMCPServer, ToolResult, ToolError

CONFIG_DIR = "/session/config"


class EvilWinRMServer(BaseMCPServer):
    """MCP server for WinRM operations using pypsrp."""

    _AUTH_PARAMS = {
        "target": {"type": "string", "required": True, "description": "Target IP or hostname"},
        "username": {"type": "string", "required": True, "description": "Username (for kerberos use user@REALM format)"},
        "password": {"type": "string", "description": "Password"},
        "hash": {"type": "string", "description": "NTLM hash for pass-the-hash (bare NT hash or LM:NT format)"},
        "domain": {"type": "string", "description": "Active Directory domain"},
        "auth": {
            "type": "enum",
            "values": ["ntlm", "kerberos"],
            "default": "ntlm",
            "description": "Auth method. Use 'kerberos' when NTLM is disabled on the target.",
        },
        "ccache_path": {
            "type": "string",
            "description": "Path to Kerberos ccache file (e.g., /session/credentials/auditor.ccache). Required when auth=kerberos.",
        },
        "ssl": {"type": "boolean", "description": "Use SSL (port 5986)"},
        "port": {"type": "integer", "description": "Custom port (default: 5985 or 5986 for SSL)"},
    }

    def __init__(self):
        super().__init__(
            name="evil-winrm",
            description="WinRM shell for command execution and file transfer",
            version="2.0.0",
        )

        self.register_method(
            name="exec",
            description="Execute command via WinRM (PowerShell or CMD)",
            params={
                **self._AUTH_PARAMS,
                "command": {"type": "string", "required": True, "description": "Command to execute"},
                "shell": {
                    "type": "enum",
                    "values": ["powershell", "cmd"],
                    "description": "Shell to use: 'powershell' (default, native PSRP) or 'cmd' (WinRS CMD shell)",
                },
            },
            handler=self.exec_cmd,
        )

        self.register_method(
            name="upload",
            description="Upload file to target via WinRM",
            params={
                **self._AUTH_PARAMS,
                "local_path": {"type": "string", "required": True, "description": "Local file path to upload"},
                "remote_path": {"type": "string", "required": True, "description": "Remote destination path"},
            },
            handler=self.upload,
        )

        self.register_method(
            name="download",
            description="Download file from target via WinRM",
            params={
                **self._AUTH_PARAMS,
                "remote_path": {"type": "string", "required": True, "description": "Remote file path to download"},
                "local_path": {"type": "string", "description": "Local destination (default: /session/artifacts/)"},
            },
            handler=self.download,
        )

    def _get_client(self, target: str, username: str, password: Optional[str] = None,
                    hash: Optional[str] = None, domain: Optional[str] = None,
                    ssl: bool = False, port: Optional[int] = None,
                    auth: str = "ntlm", ccache_path: Optional[str] = None):
        """Create a pypsrp Client.

        Authentication modes:
          - ntlm: hash (pass-the-hash) > password
          - kerberos: uses ccache file via KRB5CCNAME env var
        """
        from pypsrp.client import Client

        actual_port = port or (5986 if ssl else 5985)

        if auth == "kerberos":
            # Set KRB5CCNAME if ccache provided
            if ccache_path:
                os.environ["KRB5CCNAME"] = ccache_path
            # Ensure krb5.conf exists (may have been generated by impacket)
            shared_krb5 = os.path.join(CONFIG_DIR, "krb5.conf")
            if os.path.exists(shared_krb5) and not os.path.exists("/etc/krb5.conf"):
                shutil.copy(shared_krb5, "/etc/krb5.conf")

            client = Client(
                target,
                username=username,
                password=password or "",
                port=actual_port,
                ssl=ssl,
                auth="kerberos",
                cert_validation=False,
                connection_timeout=30,
            )
        else:
            # NTLM auth: hash takes priority over password
            if hash:
                if ":" not in hash:
                    auth_pass = f"00000000000000000000000000000000:{hash}"
                else:
                    auth_pass = hash
            else:
                auth_pass = password or ""

            client = Client(
                target,
                username=username,
                password=auth_pass,
                port=actual_port,
                ssl=ssl,
                auth="ntlm",
                cert_validation=False,
                connection_timeout=30,
            )
        return client

    def _classify_winrm_error(self, error_str: str) -> tuple:
        """Classify WinRM errors into (error_class, retryable, suggestions).

        Returns:
            (error_class, retryable, suggestions) where error_class is one of:
            auth, network, timeout, permission, config, params, unknown
        """
        err = str(error_str)

        # --- Authentication failures ---
        if "Failed to authenticate" in err:
            suggestions = ["Verify credentials (password or NTLM hash)"]
            if "ntlm" in err.lower():
                suggestions.append("If NTLM is disabled, try auth='kerberos' with a ccache file")
            return ("auth", False, suggestions)

        if re.search(r"STATUS_LOGON_FAILURE|Logon failure", err, re.IGNORECASE):
            return ("auth", False, [
                "Verify username and password/hash are correct",
                "Check if account is locked out",
            ])

        # --- Kerberos errors ---
        if "KRB_AP_ERR_SKEW" in err or "Clock skew" in err:
            return ("config", True, [
                "Clock skew detected. Retry with clock_offset parameter to sync with DC time.",
                "Example: clock_offset='+5h' or clock_offset='-30m'",
            ])

        if "KDC_ERR_PREAUTH_FAILED" in err:
            return ("auth", False, [
                "Kerberos pre-authentication failed. Password or hash is wrong.",
            ])

        if "KDC_ERR_C_PRINCIPAL_UNKNOWN" in err:
            return ("auth", False, [
                "Kerberos principal not found. Check username@REALM format.",
            ])

        # --- Network / connection errors ---
        if re.search(r"ConnectTimeout|connect timeout|connection timed out", err, re.IGNORECASE):
            return ("network", True, [
                "WinRM connection timed out. Target may be down or port 5985/5986 filtered.",
                "Verify target is reachable and WinRM service is running.",
            ])

        if re.search(r"Connection refused|ConnectionRefusedError", err, re.IGNORECASE):
            return ("network", True, [
                "Connection refused. WinRM service may not be running on target.",
                "Check if port 5985 (HTTP) or 5986 (HTTPS) is open.",
            ])

        if re.search(r"No route to host|Network is unreachable", err, re.IGNORECASE):
            return ("network", False, [
                "Target is unreachable. Check VPN connection and routing.",
            ])

        # --- Permission / access denied ---
        if re.search(r"WSManFault.*Code:\s*5|Access\s+(?:is|to the path is)\s+denied|E_ACCESSDENIED", err, re.IGNORECASE):
            return ("permission", False, [
                "Access denied. User may not be in 'Remote Management Users' group.",
                "Try with a different account or use netexec winrm for credential validation.",
            ])

        if "ConstrainedLanguage" in err or "language mode" in err.lower():
            return ("permission", False, [
                "PowerShell Constrained Language Mode active. Use shell='cmd' for basic commands.",
                "Or use simpler PowerShell that doesn't invoke restricted APIs.",
            ])

        # --- Elevation / privilege required ---
        if re.search(r"requires elevation|requires other privileges|Cannot open Service Control Manager", err, re.IGNORECASE):
            return ("permission", False, [
                "Operation requires elevated privileges. The current user is not an administrator.",
                "Try with an admin-level account or use a privilege escalation technique.",
            ])

        # --- Session / remoting failures ---
        if re.search(r"logon session does not exist|specified logon session", err, re.IGNORECASE):
            return ("auth", True, [
                "WinRM session expired or Kerberos ticket invalidated.",
                "Re-authenticate or obtain a fresh ticket.",
            ])

        if re.search(r"Connecting to remote server.*failed", err, re.IGNORECASE):
            return ("network", True, [
                "PowerShell remoting to a secondary host failed.",
                "Verify the remote host is reachable from the WinRM target and PS remoting is enabled.",
            ])

        # --- HTTP / service layer errors ---
        if re.search(r"Service Unavailable|HTTP Error 503", err, re.IGNORECASE):
            return ("network", True, [
                "WinRM HTTP service returned 503. Service may be restarting or overloaded.",
                "Retry after a brief wait.",
            ])

        # --- Timeout (server-side command execution timeout) ---
        if re.search(r"Operation timed out|timed out|TimeoutError", err, re.IGNORECASE):
            return ("timeout", True, [
                "Command execution timed out. Try a simpler/faster command.",
            ])

        return ("unknown", False, [])

    async def exec_cmd(self, target: str, username: str, command: str,
                       password: Optional[str] = None, hash: Optional[str] = None,
                       domain: Optional[str] = None, shell: str = "powershell",
                       ssl: bool = False, port: Optional[int] = None,
                       auth: str = "ntlm", ccache_path: Optional[str] = None,
                       **kwargs) -> ToolResult:
        """Execute a command via WinRM using PowerShell (PSRP) or CMD (WinRS)."""
        if kwargs:
            self.logger.debug(f"Ignoring unknown params: {list(kwargs.keys())}")
        shell_label = "CMD" if shell == "cmd" else "PowerShell"
        # Prepend domain to username for NTLM auth (skip for kerberos — use user@REALM)
        auth_user = f"{domain}\\{username}" if domain and auth != "kerberos" else username
        self.logger.info(f"WinRM exec ({shell_label}): {target} as {auth_user} [auth={auth}]")

        try:
            client = self._get_client(target, auth_user, password, hash, None, ssl, port, auth, ccache_path)

            if shell == "cmd":
                stdout, stderr, rc = client.execute_cmd(command)
            else:
                # execute_ps returns (stdout: str, streams: PSDataStreams, had_errors: bool)
                stdout, streams, had_errors = client.execute_ps(command)
                stderr = "\n".join(str(e) for e in streams.error) if streams.error else ""
                rc = 1 if had_errors else 0

            # Distinguish between command-level errors (PS errors) and auth/network errors
            if rc != 0 and stderr:
                error_class, retryable, suggestions = self._classify_winrm_error(stderr)
            else:
                error_class, retryable, suggestions = (None, False, [])

            return ToolResult(
                success=rc == 0,
                data={
                    "output": stdout.strip() if stdout else "",
                    "stderr": stderr.strip() if stderr and stderr.strip() else None,
                    "exit_code": rc,
                    "shell": shell_label,
                },
                raw_output=stdout.strip() if stdout else "",
                error=stderr.strip() if rc != 0 and stderr and stderr.strip() else None,
                error_class=error_class,
                retryable=retryable,
                suggestions=suggestions,
            )
        except Exception as e:
            error_str = str(e)
            error_class, retryable, suggestions = self._classify_winrm_error(error_str)
            return ToolResult(
                success=False,
                error=f"WinRM connection failed: {error_str}",
                data={"error": error_str},
                error_class=error_class,
                retryable=retryable,
                suggestions=suggestions,
            )

    async def upload(self, target: str, username: str, local_path: str, remote_path: str,
                     password: Optional[str] = None, hash: Optional[str] = None,
                     domain: Optional[str] = None,
                     ssl: bool = False, port: Optional[int] = None,
                     auth: str = "ntlm", ccache_path: Optional[str] = None,
                     **kwargs) -> ToolResult:
        """Upload a file to the target via WinRM using native PSRP copy."""
        if kwargs:
            self.logger.debug(f"Ignoring unknown params: {list(kwargs.keys())}")
        auth_user = f"{domain}\\{username}" if domain and auth != "kerberos" else username
        self.logger.info(f"WinRM upload: {local_path} -> {remote_path} on {target}")

        if not os.path.isfile(local_path):
            return ToolResult(
                success=False,
                error=f"Local file not found: {local_path}",
                data={},
                error_class="params",
                retryable=False,
                suggestions=["Check the local_path exists. Files should be in /session/ directory."],
            )

        try:
            client = self._get_client(target, auth_user, password, hash, None, ssl, port, auth, ccache_path)

            file_size = os.path.getsize(local_path)
            client.copy(local_path, remote_path)

            return ToolResult(
                success=True,
                data={
                    "local_path": local_path,
                    "remote_path": remote_path,
                    "size": file_size,
                },
                raw_output=f"Uploaded {file_size} bytes to {remote_path}",
            )
        except Exception as e:
            error_str = str(e)
            error_class, retryable, suggestions = self._classify_winrm_error(error_str)
            return ToolResult(
                success=False,
                error=f"Upload failed: {error_str}",
                data={},
                error_class=error_class,
                retryable=retryable,
                suggestions=suggestions,
            )

    async def download(self, target: str, username: str, remote_path: str,
                       password: Optional[str] = None, hash: Optional[str] = None,
                       domain: Optional[str] = None, local_path: Optional[str] = None,
                       ssl: bool = False, port: Optional[int] = None,
                       auth: str = "ntlm", ccache_path: Optional[str] = None,
                       **kwargs) -> ToolResult:
        """Download a file from the target via WinRM using native PSRP fetch."""
        if kwargs:
            self.logger.debug(f"Ignoring unknown params: {list(kwargs.keys())}")
        auth_user = f"{domain}\\{username}" if domain and auth != "kerberos" else username
        self.logger.info(f"WinRM download: {remote_path} from {target}")

        try:
            client = self._get_client(target, auth_user, password, hash, None, ssl, port, auth, ccache_path)

            # Determine local save path
            if not local_path:
                filename = os.path.basename(remote_path)
                local_path = f"/session/artifacts/{filename}"

            os.makedirs(os.path.dirname(local_path), exist_ok=True)
            client.fetch(remote_path, local_path)

            file_size = os.path.getsize(local_path)

            return ToolResult(
                success=True,
                data={
                    "remote_path": remote_path,
                    "local_path": local_path,
                    "size": file_size,
                },
                raw_output=f"Downloaded {file_size} bytes from {remote_path} to {local_path}",
            )
        except Exception as e:
            error_str = str(e)
            error_class, retryable, suggestions = self._classify_winrm_error(error_str)
            return ToolResult(
                success=False,
                error=f"Download failed: {error_str}",
                data={},
                error_class=error_class,
                retryable=retryable,
                suggestions=suggestions,
            )


if __name__ == "__main__":
    EvilWinRMServer.main()
